feat: select header and footer
spartan-ng/spartan pull request #409
Opened 2024-11-02 23:28 UTC by CO97

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

The current select implementation does not allow for fixed items to be added as a header or footer to the dropdown content.

Closes #400

## What is the new behavior?

This change adds flexibility without changing the functionality or structure of the existing implementation by adding two new optional directives for projecting in content to the header/footer of the dropdown.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

A real world example of where this is useful is for a select all or reset buttons to be shown in the dropdown, another example is a count of available items vs selected items.

2024-11-02 23:28 UTC, CO97 commented
Please let me know of any changes needed, this is my first time committing to an open source project and I am interested in contributing further to this one!

2024-11-06 23:21 UTC, elite-benni requested changes
Thanks for the PR!

Would you be so kind and add an e2e test for the change?

Additionally this PR reveals an existing bug in the scrolling implementation. 
I left a comment in the code. 

Kind regards

2024-11-06 23:21 UTC, elite-benni commented on libs/ui/select/brain/src/lib/brn-select-content.component.ts
The scrolling to bottom does not work smoothly when there is a footer in place. 
It is caused by the current implementation of the moveFocusDown(), which seems to use some hardcoded pixel values. 
This would also not work if someone uses a different height for the scroll button, so technically this was already a bug. 

Some quick tests with the following code seemed to fix this issue. 

```ts
public moveFocusDown() {
	const nativeElement = this.viewport.nativeElement;
	nativeElement.scrollBy({ top: 100, behavior: 'smooth' });
	const { clientHeight, scrollHeight, scrollTop } = nativeElement;
	if (clientHeight + scrollTop >= scrollHeight) {
		this.scrollDownBtn.stopEmittingEvents();
	}
}
```

2024-11-07 07:02 UTC, thatsamsonkid commented
One small concern I have is how this will behave from an Accessibility standpoint. Not sure how a screenreader would read content in this areas if it's not technically an option. Also i'm curious if this opens up the component to some kind of bad practice. Might be worth doing a manual spot check on this. Not saying we can't add but we might want to mention in docs that adding anything to complex in these areas might not be accessible or affect accessibility

2024-11-07 07:10 UTC, elite-benni commented
> One small concern I have is how this will behave from an Accessibility standpoint. Not sure how a screenreader would read content in this areas if it's not technically an option. Also i'm curious if this opens up the component to some kind of bad practice. Might be worth doing a manual spot check on this. Not saying we can't add but we might want to mention in docs that adding anything to complex in these areas might not be accessible or affect accessibility

good point!

2024-11-08 13:08 UTC, CO97 commented
I have thought about this implementation further, the issue arises because of the content having the scrolling functionality built into the dropdown and this is more of a bandade than addressing the underlying issue. Would it be better to break out the scrollable area into a separate component that can be used or ignored if a developer wanted to use their own simple scroll with overflow y on the container?

It would allow total customization of the layout within the content. I would be interested to hear your opinions on this?

```
<brn-select class="inline-block" placeholder="Select an option">
      <hlm-select-trigger class="w-56">
        <hlm-select-value />
      </hlm-select-trigger>
      <hlm-select-content>
        <hlm-select-content-scroll> <-- New scroll component?
            <hlm-option value="Refresh">Refresh</hlm-option>
            <hlm-option value="Settings">Settings</hlm-option>
            <hlm-option value="Help">Help</hlm-option>
            <hlm-option value="Signout">Sign out</hlm-option>
        <hlm-select-content-scroll>
      </hlm-select-content>
    </brn-select>
```

2024-11-11 00:25 UTC, closed without merging